# Generated by Django 4.0.2 on 2022-03-05 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='followuser',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='followuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResetPasswordCode',
        ),
    ]
