# Generated by Django 3.2.7 on 2021-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_authorized',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
