# Generated by Django 3.2.7 on 2021-09-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210929_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='code',
            new_name='id',
        ),
    ]
