# Generated by Django 3.2.7 on 2021-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211124_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adult_content',
            field=models.BooleanField(default=True),
        ),
    ]
