# Generated by Django 3.2.7 on 2021-11-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile_adult_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='to_follow',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='blockuser',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportuser',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_users', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportuser',
            name='report',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportuser',
            name='title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockuser',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blockuser',
            unique_together={('created_by', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('created_by', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reportuser',
            unique_together={('created_by', 'user')},
        ),
        migrations.RemoveField(
            model_name='blockuser',
            name='to_block',
        ),
        migrations.RemoveField(
            model_name='reportuser',
            name='to_report',
        ),
    ]
