# Generated by Django 4.0.2 on 2022-03-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deactivation_reason',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deactivated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
