# Generated by Django 3.2.7 on 2021-09-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_code_profile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpasswordcode',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='resetpasswordcode',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profileavatar',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='profilecover',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='account.profile'),
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
