# Generated by Django 4.0.2 on 2022-03-21 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_deactivated_at_profile_deactivation_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='gender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 21, 18, 10, 19, 57592, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
