# Generated by Django 3.2.7 on 2021-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='comment_update_limit',
            field=models.PositiveIntegerField(default=30, help_text='in days'),
        ),
    ]
