# Generated by Django 4.0.2 on 2022-03-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
        ('account', '0005_rename_user_gender_created_by_and_more'),
        ('share', '0001_initial'),
        ('vote', '0001_initial'),
        ('report', '0001_initial'),
        ('comment', '0001_initial'),
        ('community', '0002_rename_subscriber_subscription_created_by_and_more'),
        ('publication', '0003_alter_recentpublication_unique_together'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookmark.bookmark'),
        ),
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.followuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='report.report'),
        ),
        migrations.AddField(
            model_name='notification',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='share.share'),
        ),
        migrations.AddField(
            model_name='notification',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vote.vote'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.community'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.subscription'),
        ),
    ]
