# Generated by Django 3.2.7 on 2021-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.AddField(
            model_name='notificationto',
            name='seen',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
