# Generated by Django 4.0.2 on 2022-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hide',
            name='community',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden', to='community.community'),
        ),
        migrations.AlterField(
            model_name='hide',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_hides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hide',
            name='publication',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden', to='publication.publication'),
        ),
    ]
