# Generated by Django 4.0.2 on 2022-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hide',
            name='unique_community_user_hide',
        ),
        migrations.RemoveField(
            model_name='hide',
            name='community',
        ),
    ]
