# Generated by Django 4.0.2 on 2022-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hide', '0002_hide_community_alter_hide_created_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hide',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', False)), fields=('community', 'created_by'), name='unique_community_user_hide'),
        ),
    ]
