# Generated by Django 4.0.2 on 2022-03-05 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_delete_communityauthorizationcode'),
        ('auth_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorizationcode',
            name='unique_community_auth_code',
        ),
        migrations.RemoveConstraint(
            model_name='authorizationcode',
            name='unique_user_auth_code',
        ),
        migrations.AlterField(
            model_name='authorizationcode',
            name='community',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_code', to='community.community'),
        ),
        migrations.AlterField(
            model_name='authorizationcode',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
