# Generated by Django 4.0.2 on 2022-03-21 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('created_by', 'community')},
        ),
    ]
