# Generated by Django 4.0.3 on 2023-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='quote',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='welcome_text',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
