# Generated by Django 3.2.7 on 2021-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityavatar',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='communitycover',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
