# Generated by Django 4.0.2 on 2022-02-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_communityreport_resolver_communityreport_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityreport',
            name='resolver',
        ),
        migrations.AddField(
            model_name='communityreport',
            name='resolve_text',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='resolved_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='resolved_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', editable=False, max_length=8),
        ),
    ]
