# Generated by Django 3.2.7 on 2021-09-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityadmin_communityhashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityadmin',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='communityadmin',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='community.community'),
            preserve_default=False,
        ),
    ]
