# Generated by Django 4.0.2 on 2022-03-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityAuthorizationCode',
        ),
    ]
