# Generated by Django 4.0.2 on 2022-03-05 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_delete_communityauthorizationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mod', 'Moderator'), ('sub', 'Sub Moderator')], max_length=3)),
                ('is_accepted', models.BooleanField(default=False, editable=False)),
                ('accepted_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_notification', models.BooleanField(default=False, editable=False)),
                ('is_approved', models.BooleanField(default=False, editable=False)),
                ('approved_at', models.DateTimeField(editable=False, null=True)),
                ('is_banned', models.BooleanField(default=False, editable=False)),
                ('ban_reason', models.TextField(editable=False, null=True)),
                ('banned_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='CommunityRule',
            new_name='Rule',
        ),
        migrations.RenameModel(
            old_name='CommunityTheme',
            new_name='Theme',
        ),
        migrations.AlterUniqueTogether(
            name='communitysubadmin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communitysubadmin',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitysubadmin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='communitysubadmin',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='communitysubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communitysubscription',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitysubscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='CommunityAdmin',
        ),
        migrations.DeleteModel(
            name='CommunitySubAdmin',
        ),
    ]
