# Generated by Django 3.2.7 on 2021-11-12 11:48

import community.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_completed_registration_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='unique_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, validators=[community.models.validate_unique_id]),
            preserve_default=False,
        ),
    ]
