# Generated by Django 4.0.2 on 2022-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_communityreport_resolver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreport',
            name='resolve_text',
            field=models.TextField(editable=False, null=True),
        ),
    ]
