# Generated by Django 4.0.2 on 2022-03-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_subscription'),
        ('community', '0004_moderator_subscription_rename_communityrule_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunitySubscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='community',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='community.community'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderator',
            name='community',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='community.community'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_community_moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='moderator',
            unique_together={('user', 'community', 'role')},
        ),
    ]
