# Generated by Django 3.2.7 on 2021-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityrule',
            old_name='rule',
            new_name='description',
        ),
        migrations.AddField(
            model_name='communityrule',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='communityrule',
            unique_together={('community', 'title')},
        ),
    ]
