# Generated by Django 3.2.7 on 2021-11-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20211112_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityhashtag',
            old_name='publication',
            new_name='community',
        ),
    ]
