# Generated by Django 3.2.7 on 2021-11-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('community', '0006_rename_publication_communityhashtag_community'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityhashtag',
            unique_together={('tag', 'community')},
        ),
    ]
