# Generated by Django 3.2.7 on 2021-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_communityhashtag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmin',
            name='accepted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='communityadmin',
            name='is_accepted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
