# Generated by Django 3.2.7 on 2021-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20211119_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
