# Generated by Django 3.2.7 on 2021-11-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20211121_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='welcome_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityadmin',
            name='community',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='community.community'),
        ),
        migrations.AlterField(
            model_name='communitysubadmin',
            name='community',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sub_admins', to='community.community'),
        ),
    ]
