# Generated by Django 3.2.7 on 2021-11-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20211122_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityrule',
            options={'ordering': ['timestamp']},
        ),
    ]
