# Generated by Django 3.2.7 on 2021-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_communityrule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='quote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='welcome_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='communityadmin',
            name='accepted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='approved_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='banned_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
