# Generated by Django 3.2.7 on 2021-11-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20211122_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitycreateprogress',
            options={'ordering': ['timestamp']},
        ),
    ]
