# Generated by Django 4.0.2 on 2022-02-11 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import publication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, editable=False)),
                ('published_at', models.DateTimeField(editable=False, null=True)),
                ('is_pinned', models.BooleanField(default=False, editable=False)),
                ('views', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=16, null=True)),
                ('type', models.CharField(choices=[('editor', 'Editor'), ('media', 'Media'), ('link', 'Link'), ('poll', 'Poll')], default='editor', max_length=32)),
                ('popularity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('dislikes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('supports', models.PositiveBigIntegerField(default=0, editable=False)),
                ('discussions', models.PositiveBigIntegerField(default=0, editable=False)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='community.community')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PublicationImageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image_urls', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=publication.models.upload_publication_image_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PublicationUpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_voted_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_votes', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PublicationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tags', models.CharField(blank=True, max_length=16, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PublicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(editable=False, max_length=512, null=True)),
                ('image', models.URLField(editable=False, null=True)),
                ('description', models.TextField(editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publication', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'link')},
            },
        ),
        migrations.CreateModel(
            name='PublicationHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='hashtag.hashtag')),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'hashtag')},
            },
        ),
        migrations.CreateModel(
            name='PublicationDownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_voted_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_votes', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PublicationBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='saved_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='HidePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hides', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'created_by')},
            },
        ),
    ]
