# Generated by Django 4.0.2 on 2022-03-04 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, editable=False)),
                ('published_at', models.DateTimeField(editable=False, null=True)),
                ('is_pinned', models.BooleanField(default=False, editable=False)),
                ('views', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=16, null=True)),
                ('type', models.CharField(choices=[('editor', 'Editor'), ('media', 'Media'), ('link', 'Link'), ('poll', 'Poll')], default='editor', max_length=32)),
                ('popularity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('dislikes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('supports', models.PositiveBigIntegerField(default=0, editable=False)),
                ('discussions', models.PositiveBigIntegerField(default=0, editable=False)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='community.community')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PublicationHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='hashtag.hashtag')),
                ('publication', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='publication.publication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('publication', 'hashtag')},
            },
        ),
    ]
