# Generated by Django 3.2.7 on 2021-11-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='PublicationHashtag',
        ),
    ]
