# Generated by Django 3.2.7 on 2021-11-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='view_count',
            new_name='views',
        ),
    ]
