# Generated by Django 3.2.7 on 2021-11-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20211114_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('editor', 'Editor'), ('media', 'Media'), ('link', 'Link'), ('poll', 'Poll')], default='editor', max_length=32),
        ),
    ]
