# Generated by Django 4.0.2 on 2022-03-21 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_recentpublication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentpublication',
            unique_together={('publication', 'created_by')},
        ),
    ]
