# Generated by Django 3.2.7 on 2021-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationlink',
            name='metadata',
        ),
        migrations.AddField(
            model_name='publicationlink',
            name='description',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publicationlink',
            name='image',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publicationlink',
            name='title',
            field=models.CharField(editable=False, max_length=512, null=True),
        ),
    ]
