# Generated by Django 3.2.7 on 2021-11-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20211115_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlink',
            name='publication',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='publication.publication'),
        ),
    ]
