# Generated by Django 3.2.7 on 2021-11-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_alter_publicationlink_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlink',
            name='publication',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='publication.publication'),
        ),
    ]
