# Generated by Django 3.2.7 on 2021-11-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0007_publicationshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidepublication',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationdownvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationshare',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationupvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
