# Generated by Django 3.2.7 on 2021-11-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0008_auto_20211118_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationbookmark',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationdownvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationupvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportpublication',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
