# Generated by Django 3.2.7 on 2021-11-21 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_auto_20211118_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationbookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 21, 13, 44, 19, 600679, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
