# Generated by Django 3.2.7 on 2021-11-23 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0010_publicationbookmark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidepublication',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationbookmark',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='saved_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationdownvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_voted_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationshare',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicationupvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_voted_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportpublication',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
