# Generated by Django 3.2.7 on 2021-11-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_publicationhashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationhashtag',
            name='publication',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hash_tags', to='publication.publication'),
        ),
    ]
