# Generated by Django 3.2.7 on 2021-11-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('publication', '0013_alter_publicationhashtag_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationhashtag',
            name='hashtag',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='hashtag.hashtag'),
        ),
        migrations.AlterField(
            model_name='publicationhashtag',
            name='publication',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='publication.publication'),
        ),
    ]
