# Generated by Django 4.0.3 on 2023-05-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_reason', models.TextField()),
                ('ban_item_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('ban_item_app_label', models.CharField(choices=[('publication', 'publication'), ('comment', 'comment'), ('account', 'account'), ('community', 'community')], max_length=32)),
                ('ban_item_model', models.CharField(choices=[('publication', 'publication'), ('comment', 'comment'), ('profile', 'profile'), ('community', 'community')], max_length=32)),
                ('banned_at', models.DateTimeField(editable=False, null=True)),
                ('banned_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-banned_at'],
                'unique_together': {('ban_item_id', 'ban_item_model')},
            },
        ),
    ]
