# Generated by Django 4.0.3 on 2023-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='ban_item_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
