# Generated by Django 3.2.7 on 2021-10-01 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDownVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('down_vote', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommentUpVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('up_vote', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='commentimageurl',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='commentvideourl',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentimageurl',
            name='comment',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image_urls', to='comment.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentvideourl',
            name='comment',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='comment.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_comments', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='comment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='comment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment.comment'),
        ),
        migrations.DeleteModel(
            name='DownVotes',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
        migrations.AddField(
            model_name='commentupvote',
            name='comment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_votes', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='commentupvote',
            name='writer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_voted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentdownvote',
            name='comment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_votes', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='commentdownvote',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='down_voted_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
