# Generated by Django 3.2.7 on 2021-11-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_auto_20211118_2352'),
        ('comment', '0003_auto_20211120_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publication.publication'),
        ),
    ]
