# Generated by Django 3.2.7 on 2021-11-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_publication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hidereply',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hidereply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hidereply',
            name='reply',
        ),
        migrations.AlterUniqueTogether(
            name='replybookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replybookmark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='replybookmark',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replyimage',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replyimageurl',
            name='reply',
        ),
        migrations.AlterUniqueTogether(
            name='replylink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replylink',
            name='reply',
        ),
        migrations.AlterUniqueTogether(
            name='replyshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replyshare',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='replyshare',
            name='reply',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='HideReply',
        ),
        migrations.DeleteModel(
            name='ReplyBookmark',
        ),
        migrations.DeleteModel(
            name='ReplyImage',
        ),
        migrations.DeleteModel(
            name='ReplyImageUrl',
        ),
        migrations.DeleteModel(
            name='ReplyLink',
        ),
        migrations.DeleteModel(
            name='ReplyShare',
        ),
    ]
