# Generated by Django 3.2.7 on 2021-11-23 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0005_auto_20211121_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbookmark',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='saved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentshare',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hidecomment',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
