name: action-git-diff-suggestions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: action-git-diff-suggestions
     - uses: getsentry/action-git-diff-suggestions@v1

