name: LintsAndChecks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: action-git-diff-suggestions
        uses: getsentry/action-git-diff-suggestions@v1
      - name: python-linter
        uses: sunnysid3up/python-linter@v0.1-beta.7
        with:
          source: "./"
          isort-options: "-w 100"
          django: true
      

