name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy ci environment
      run: |
        cp .env.ci .env
        ls -la
        cat .env

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Lint with flake8
      run: make lint-with-flake8

    - name: Black analysis
      run: make black-check

    - name: Unit Tests
      run: make test